name: gpmp
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.6.0=h26f9b46_0
  - pandas=2.2.2=py39hfc16268_1
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.25=h0dcde21_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.1=pyhd8ed1ab_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py39h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - asttokens==3.0.1
      - astunparse==1.6.3
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - check-shapes==1.1.1
      - cloudpickle==3.1.2
      - comm==0.2.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - deprecated==1.3.1
      - dm-tree==0.1.8
      - dropstackframe==0.1.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - gast==0.6.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.3
      - google-pasta==0.2.0
      - gpflow==2.10.0
      - grpcio==1.76.0
      - h5py==3.14.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipykernel==6.31.0
      - ipython==8.18.1
      - jedi==0.19.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - keras==2.15.0
      - kiwisolver==1.4.7
      - lark==1.3.1
      - libclang==18.1.1
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - ml-dtypes==0.3.2
      - multipledispatch==1.0.0
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.2.5.6
      - nvidia-cuda-cupti-cu12==12.2.142
      - nvidia-cuda-nvcc-cu12==12.2.140
      - nvidia-cuda-nvrtc-cu12==12.2.140
      - nvidia-cuda-runtime-cu12==12.2.140
      - nvidia-cudnn-cu12==8.9.4.25
      - nvidia-cufft-cu12==11.0.8.103
      - nvidia-curand-cu12==10.3.3.141
      - nvidia-cusolver-cu12==11.5.2.141
      - nvidia-cusparse-cu12==12.1.2.141
      - nvidia-nccl-cu12==2.16.5
      - nvidia-nvjitlink-cu12==12.2.140
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - packaging==25.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.4.0
      - prompt-toolkit==3.0.52
      - protobuf==4.25.8
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pyzmq==27.1.0
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scipy==1.13.1
      - six==1.17.0
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-probability==0.23.0
      - termcolor==3.1.0
      - tornado==6.5.2
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - wrapt==1.14.2
      - zipp==3.23.0
prefix: /home/abbas/miniconda3/envs/gpmp
